#!/bin/sh

# in case you need to know in which directory this script is running, use command:
# echo "$PWD"

################
### back-end ###
################
if git diff --staged --name-only HEAD | grep "back_end"; then # run this section, only if in staged area something was edited from back_end
echo "---------------------------------back-end pre commit section---------------------------------"

echo "Checking code style format. Running mvn spotless:check"
mvn spotless:check -q

if [ $? -ne 0 ]; then
    echo "Code style check failed. Running mvn spotless:apply to fix..."

    mvn spotless:apply -q
    mvn spotless:check -q

    if [ $? -ne 0 ]; then
        echo "Code style check failed even after applying changes. Check if plugin configured correctly or fix the issues manually."
        exit 1
    fi

    echo "Code style issues fixed. Run commit again."
    exit 1
fi
echo "Code style format is ok."
fi
